import type { Metadata } from "next";
import { Saira } from "next/font/google";
import ThemeProviderClient from "@/core_components/theme/ThemeProviderClient";
import TopBar from "@/core_components/topbar/topbar";
import ReduxProvider from "@/core_components/state/ReduxProvider";
import { getSession } from "@/core_components/auth/getSession";
import FeatureFlagsServerProvider from "@/core_components/feature_flags/FeatureFlagsServerProvider";

const saira = Saira({ subsets: ['latin'], weight: ['400', '500', '600', '700'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const dynamic = "force-dynamic";

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const demoSession = await getSession();
  const preloadedState = demoSession ? { auth: { user: { username: demoSession.username } } } : undefined;
  return (
    <html lang="en">
      <body className={saira.className}>
        <ThemeProviderClient>
          <ReduxProvider preloadedState={preloadedState}>
            <FeatureFlagsServerProvider>
              <TopBar />
              {children}
            </FeatureFlagsServerProvider>
          </ReduxProvider>
        </ThemeProviderClient>
      </body>
    </html>
  );
}
